[supervisord]
nodaemon=true
user=root
logfile=/var/log/nsupervisord.log
pidfile=/var/log/nsupervisord.pid

[program:nextjs]
command=/bin/sh -c "fuser -k 80/tcp || true && npm run start -- -p 80"
user=root
directory=/app
autostart=true
autorestart=true
startretries=3
startsecs=5
stopasgroup=true
killasgroup=true
stdout_logfile=/var/log/next.out.log
stderr_logfile=/var/log/next.err.log

# [program:nginx]
# command=nginx -g "daemon off;"
# user=root
# autostart=true
# autorestart=true
# stdout_logfile=/var/log/nginx.out.log
# stderr_logfile=/var/log/nginx.err.log